.dependabot/config.yml
Будет присылать обновления зависимостей и автоматически мёржить security обновления
=> Добавил конфиг депендабота

packages/core-design/src/components/SubHeading/SubHeading.stories.tsx, packages/core-design/src/components/SubHeading/SubHeading.styles.ts, packages/core-design/src/components/SubHeading/SubHeading.tsx, packages/core-design/src/styles/fonts.ts, packages/core-design/src/themes/default.ts
BREAKING CHANGE: обновил стили текстовых компонентов согласно новому дизайну com
- ссылка на jira: https://jira.csssr.io/browse/COM-1056
- стенд: http://feat-com-1056.cre-design.csssr.ru
=> feat: COM-1056

.gitignore, .vscode/settings.json, packages/core-design/src/components/Button/Button.stories.tsx, packages/core-design/src/components/Button/Button.styles.ts, packages/core-design/src/components/Button/Button.tsx, yarn.lock
- ссылка на jira: https://jira.csssr.io/browse/COM-1592
=> feat: COM-1592 добавляет кнопке новую тему

packages/core-design/src/components/Footer/SocialLinks/SocialLinks.styles.ts
- ссылка на jira: https://jira.csssr.io/browse/COM-2928
- стенд: http://feat-com-2928.cre-design.csssr.ru
=> feat: COM-2928 Align social media icons

packages/core-design/src/components/Header/Menu/Nav/Nav.styles.ts, packages/core-design/src/components/Header/Menu/Nav/Nav.tsx, packages/core-design/src/components/Header/types.ts, yarn.lock
=> feat: COM-3109 Актуализировал вид ссылок в хедере

packages/core-design/src/components/Header/Header.stories.tsx, packages/core-design/src/components/Header/Header.tsx, packages/core-design/src/components/Header/Menu/Menu.tsx, packages/core-design/src/components/Header/Menu/Nav/Nav.styles.ts, packages/core-design/src/components/Header/Menu/Nav/Nav.tsx, packages/core-design/src/components/Header/types.ts, packages/core-design/src/data/headerLinks.ts, packages/core-design/src/data/headerPresets.ts, packages/core-design/src/static/icons/header/computer.svg, packages/core-design/src/static/icons/header/ourProjects.svg
=> fix(header): COM-3109 update header styles, data

.github/kuberta.yaml, .github/workflows/build-storybook.yaml, packages/core-design/src/data/footerLinks.ts
Дополнительно исправил названия svg файлов в footerLinks.ts, так как не проходила сборка storybook
=> Релиз storybook через Github Workflow

packages/core-design/src/data/footerLinks.ts
=> feat: COM-3241 Footer| Changed 'Contact us' to 'Contacts'

packages/core-design/src/components/CookiesPopup/CookiesPopup.styles.ts, packages/core-design/src/components/CookiesPopup/CookiesPopup.tsx
- add size styles for close icon
=> fix(components): COM-3337 CookiesPopup

packages/core-design/src/data/cookiesPopupLinks.ts
=> fix(components): COM-3408 fix cookies popup  privacy links

packages/core-design/src/data/footerLinks.ts
=> fix(components): COM-3271 Footer links changed

packages/core-design/.storybook/config.js, packages/core-design/src/components/ErrorPage404/ErrorPage404.stories.tsx, packages/core-design/src/components/ErrorPage404/ErrorPage404.styles.ts, packages/core-design/src/components/ErrorPage404/ErrorPage404.tsx, packages/core-design/src/components/ErrorPage404/index.ts, packages/core-design/src/components/ErrorPage404/types.ts, packages/core-design/src/index.ts
=> feat(components): COM-3432 Add ErrorPage404

packages/core-design/src/data/fontsPresets.ts
=> fix(fonts): COM-3481 Refactoring font's preset

packages/core-design/babel.config.js, packages/core-design/src/components/Header/Header.styles.ts
=> fix: COM-3529 Fixed 'removeViewBox' option & fixed size of burger icon

packages/core-design/src/data/headerLinks.ts
=> fix: COM-3530 Header|  Fixed links of vacancies

packages/core-design/src/components/Header/Header.styles.ts
=> fix(Header): COM-3582 Fix mobile logo margin

packages/core-design/src/components/Footer/DoubleBottom/Addresses/Addresses.tsx
=> feat(footer): COM-3591 Add testid in DoubleBottom

.github/kuberta.yaml
=> feat: COM-3160 Add slack notifications about builds

packages/core-design/src/components/Footer/Footer.stories.tsx, packages/core-design/src/components/Footer/Footer.tsx, packages/core-design/src/components/Footer/types.ts, packages/core-design/src/data/footerLinks.ts
=> feat(footer): COM-3621 Add baseNavUrl

packages/core-design/src/components/Footer/Footer.styles.ts
=> fix(footer): COM-3330 Fix gray line in top

packages/core-design/.storybook/styles/global.js, packages/core-design/src/components/Footer/BottomLinksAndLanguages/BottomLinksAndLanguages.styles.ts, packages/core-design/src/components/Footer/DoubleBottom/Addresses/Addresses.styles.ts, packages/core-design/src/components/Footer/DoubleBottom/DoubleBottom.styles.ts, packages/core-design/src/components/Footer/Footer.styles.ts, packages/core-design/src/components/Footer/Nav/Nav.styles.ts, packages/core-design/src/components/Footer/SocialLinks/SocialLinks.styles.ts, packages/core-design/src/data/footerLinks.ts
=> fix: COM-3611 Align footer element

packages/core-design/.storybook/styles/global.js, packages/core-design/src/components/Footer/BottomLinksAndLanguages/BottomLinksAndLanguages.styles.ts, packages/core-design/src/components/Footer/DoubleBottom/Addresses/Addresses.styles.ts, packages/core-design/src/components/Footer/DoubleBottom/DoubleBottom.styles.ts, packages/core-design/src/components/Footer/Footer.stories.tsx, packages/core-design/src/components/Footer/Footer.styles.ts, packages/core-design/src/components/Footer/Footer.tsx, packages/core-design/src/components/Footer/Nav/Nav.styles.ts, packages/core-design/src/components/Footer/SocialLinks/SocialLinks.styles.ts, packages/core-design/src/components/Footer/types.ts, packages/core-design/src/data/footerLinks.ts
Jira: https://jira.csssr.io/projects/COM/versions/12822
Storybook: https://release-core-22.core-design-storybook.csssr.cloud
=> Release: Core-22

packages/core-design/src/components/Footer/DoubleBottom/Addresses/Addresses.tsx, packages/core-design/src/components/Footer/DoubleBottom/DoubleBottom.tsx, packages/core-design/src/components/Footer/Footer.stories.tsx, packages/core-design/src/components/Footer/Footer.tsx
Так же удалил пропс isIe11 из футера, потому что мы больше не поддерживаем ie11 на наших проектах
=> COM-3652 trigger `listener()` on first render

packages/core-design/src/components/CookiesPopup/CookiesPopup.styles.ts, packages/core-design/src/components/CookiesPopup/CookiesPopup.tsx, packages/core-design/src/components/Footer/BottomLinksAndLanguages/BottomLinksAndLanguages.tsx, packages/core-design/src/components/Footer/DoubleBottom/DoubleBottom.styles.ts, packages/core-design/src/components/Footer/DoubleBottom/DoubleBottom.tsx
=> COM-3744: Fix footer icons

packages/core-design/src/data/footerLinks.ts
=> fix(Footer): COM-3686 Fix footer text

packages/core-design/src/components/Footer/DoubleBottom/DoubleBottom.styles.ts
=> fix(Footer): COM-3723 Fix footer padding

packages/core-design/src/data/footerLinks.ts
=> fix(footer): COM-3761 Fix footer links

packages/core-design/src/data/footerLinks.ts
=> fix(footer): COM-3776 remove DesignLab from footer links

packages/core-design/src/data/headerLinks.ts
Заменил слово «курсы» на «материалы» в хэдере лендинга школы, убрал слово «Курсы» из коротких описаний внутри меню
=> feat: CORE-134 

packages/core-design/package.json, packages/core-design/src/data/footerLinks.ts
- https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
- стенд: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud
- комментарии к решению задачи
- документация по добавленным библиотекам
- скриншоты
=> feat: fix tg link
